import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/Footer";
import { SmoothCursor } from "@/components/ui/smooth-cursor";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "SourceCatch Konnect Private Limited | Digital Marketing ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} antialiased`}>
        <Header />
        {children}
        <SmoothCursor />
        <Footer />
      </body>
    </html>
  );
}
