import { Open_Sans, Passion_One } from "next/font/google";
import "./globals.css";

import { AnimatePresence, motion } from "motion/react";

import Header from "./(client)/components/header/Header";
import Footer from "./(client)/components/Footer";
import PageTransition from "./(client)/components/PageTransition";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});
const passionOne = Passion_One({
  variable: "--font-passion-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "SourceCatch Konnect Private Limited | Digital Marketing ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${openSans.variable} ${passionOne.variable} !overflow-x-hidden  antialiased`}
      >
        <Header />
        <PageTransition>{children}</PageTransition>
        {/* <SmoothCursor /> */}
        <Footer />
      </body>
    </html>
  );
}
